# Understand how the profiling work in Spring Boot

server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/spring-boot-pro-dev?createDatabaseIfNotExist=true
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoint:
    web:
        exposure:
            include: "*"
            exclude: "env"

test:
  application:
    properties: This is a test message from application.properties